"""Build/check one reviewable, standalone Volatility plugin from development modules.

This is static source assembly, not an exec/base64 loader. Only Python stdlib
and Volatility imports remain in the distributable. No build step at runtime.
"""
import argparse
import ast
import hashlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'src' / 'network_analysis'
TARGET = ROOT / 'src' / 'plugins' / 'inspect_networks.py'
MODULES = ('identity','topology','sockets','routes','neighbors','conntrack','multicast','presentation','collector','plugin')


def build():
    trees = {m: ast.parse((SOURCE / (m+'.py')).read_text(encoding='utf-8')) for m in MODULES}
    functions = {m: {n.name for n in t.body if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))} for m,t in trees.items()}
    class Rewrite(ast.NodeTransformer):
        def __init__(self, module):
            self.module=module
        def visit_ImportFrom(self,node):
            return None if node.level else node
        def visit_FunctionDef(self,node):
            # Only top-level functions are renamed separately below.
            return self.generic_visit(node)
        def visit_Name(self,node):
            if node.id in functions[self.module]:
                node.id=self.module+'_'+node.id
            elif self.module=='plugin' and node.id=='table':
                node.id='presentation_table'
            return node
        def visit_Attribute(self,node):
            if isinstance(node.value,ast.Name) and node.value.id in functions and node.attr in functions[node.value.id]:
                return ast.copy_location(ast.Name(id=node.value.id+'_'+node.attr,ctx=node.ctx),node)
            return self.generic_visit(node)
    sections=[]
    for module,tree in trees.items():
        tree=Rewrite(module).visit(tree)
        for node in tree.body:
            if isinstance(node,(ast.FunctionDef,ast.AsyncFunctionDef)):
                node.name=module+'_'+node.name
        ast.fix_missing_locations(tree)
        sections.append('# Source section: '+module+'\n'+ast.unparse(tree))
    result='# Generated by scripts/build_network_plugin.py; edit src/network_analysis/*.py.\n# Standalone deployment: this file + stock Volatility 3 + matching kernel ISF.\n\n'+'\n\n'.join(sections)+'\n'
    compile(result,str(TARGET),'exec')
    for node in ast.walk(ast.parse(result)):
        if isinstance(node,ast.ImportFrom) and node.level:
            raise ValueError('Relative import remains in standalone build')
    return result


if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    result=build()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding='utf-8')!=result:
            raise SystemExit('Standalone plugin is stale; rebuild it.')
    else:
        TARGET.write_text(result,encoding='utf-8',newline='\n')
    print('Standalone plugin SHA256:',hashlib.sha256(result.encode()).hexdigest())
