# Generated by scripts/build_network_plugin.py; edit src/network_analysis/*.py.
# Standalone deployment: this file + stock Volatility 3 + matching kernel ISF.

# Source section: identity
"""Runtime argv evidence supplements cgroups without treating ancestry as proof."""
import re

def identity_collect(c, records):
    by_address = {r['address']: r for r in records}
    shims, published = ({}, [])
    for task in c.tasks:
        record = by_address.get(hex(task.vol.offset))
        if record is None:
            continue

        def parent():
            return hex(int(task.real_parent))
        record['parent'] = c.read('task.parent', task, parent)
        comm = record['comm']
        if record['pid'] != record['tgid']:
            continue
        if not (comm.startswith('containerd-shim') or comm == 'docker-proxy'):
            continue
        if c.identity_mode == 'cgroup' and comm.startswith('containerd-shim'):
            continue

        def argv():
            if not task.mm:
                return []
            start, end = (int(task.mm.arg_start), int(task.mm.arg_end))
            if not 0 <= end - start <= 65536:
                raise ValueError('runtime argv length out of bounds')
            name = task.add_process_layer()
            if name is None:
                raise ValueError('runtime process layer unavailable')
            return c.context.layers[name].read(start, end - start).decode('utf-8', errors='replace').split('\x00')
        args = c.read('identity.runtime_argv', task, lambda: c.measure('identity.shim_argv', argv), [])
        if comm.startswith('containerd-shim'):
            ids = [args[i + 1] for i, arg in enumerate(args[:-1]) if arg in ('-id', '--id') and re.fullmatch('[0-9a-f]{64}', args[i + 1])]
            if ids:
                shims[record['address']] = sorted(set(ids))
                record['shim_container_candidates'] = shims[record['address']]
        else:
            flags = ('-host-ip', '-host-port', '-container-ip', '-container-port', '-proto')
            values = {arg[1:]: args[i + 1] for i, arg in enumerate(args[:-1]) if arg in flags}
            if values:
                published.append({'pid': record['pid'], 'task': record['address'], 'namespace': record.get('namespace'), 'mapping': values, 'source': 'docker-proxy argv', 'confidence': 'runtime_configuration', 'limitation': 'not proof of a matching NAT rule or successful forwarding'})
    if c.identity_mode == 'cgroup':
        for ns in c.nets.values():
            ns['container_candidates'] = sorted({cid for r in records if r.get('namespace') == ns['address'] for cid in r['container_candidates']})
        return published
    for record in records:
        node, seen = (record, set())
        while node.get('parent') in by_address:
            address = node['parent']
            if address in seen or len(seen) >= c.limit:
                c.issue('identity.ancestry', record['address'], ValueError('parent cycle/limit'))
                break
            seen.add(address)
            c.count('objects_visited', 'task_ancestry')
            if address in shims:
                record['shim_ancestry_candidates'] = shims[address]
                if not record['container_candidates']:
                    record['container_candidates'] = shims[address]
                    record['identity_evidence'] = 'shim_argv_ancestry_candidate'
                elif set(record['container_candidates']) != set(shims[address]):
                    record['identity_conflict'] = True
                break
            node = by_address[address]
    for ns in c.nets.values():
        ns['container_candidates'] = sorted({cid for r in records if r.get('namespace') == ns['address'] for cid in r['container_candidates']})
    return published

# Source section: topology
"""Direct adjacency and separately labelled private-data peer candidates."""
from volatility3.framework import objects

def topology_collect(c):
    edges, unsupported = ([], [])
    for dev, row in c.devices.values():

        def adjacent():
            if not dev.has_member('adj_list'):
                unsupported.append({'feature': 'upper_adjacency', 'interface': row['address'], 'reason': 'net_device.adj_list absent'})
                return
            for adj in c.walk(dev.adj_list.upper, 'netdev_adjacent', 'list'):
                target = int(adj.dev)
                edges.append({'kind': 'upper', 'source': row['address'], 'target': hex(target), 'master': bool(adj.master), 'evidence': hex(adj.vol.offset), 'confidence': 'direct_pointer'})
                other = c.devices.get(target)
                if other and other[1].get('kind') == 'bridge' and c.kernel.has_type('net_bridge_port') and dev.has_member('rx_handler_data') and dev.rx_handler_data:
                    port = c.obj('net_bridge_port', int(dev.rx_handler_data))
                    if int(port.dev) != dev.vol.offset or int(port.br.dev) != target:
                        raise ValueError('bridge port backlink mismatch')
                    edges.append({'kind': 'bridge_port', 'source': row['address'], 'target': hex(target), 'port_no': int(port.port_no), 'state': int(port.state), 'evidence': hex(port.vol.offset), 'confidence': 'validated_backlinks'})
        c.read('topology.upper', dev, adjacent)
        if row.get('kind') == 'veth':

            def peer():
                if not dev.has_member('priv'):
                    unsupported.append({'feature': 'veth_peer', 'interface': row['address'], 'reason': 'no symbol-described private pointer; inline alignment not assumed'})
                    return
                private_address = dev.priv.vol.offset if isinstance(dev.priv, objects.Array) else int(dev.priv)
                if not c.kernel.has_type('veth_priv'):
                    unsupported.append({'feature': 'typed_veth_peer', 'interface': row['address'], 'reason': 'veth_priv absent; reciprocal private-data references are candidates, not typed peer proof'})
                    if not isinstance(dev.priv, objects.Array) or not dev.has_member('priv_len'):
                        return
                    size = int(dev.priv_len)
                    if not 0 <= size <= 65536:
                        raise ValueError('invalid netdev private length')
                    width = c.kernel.get_type('pointer').size
                    matches = []
                    for offset in range(0, size - width + 1, width):
                        target = int(c.obj('pointer', private_address + offset)) & c.layer.address_mask
                        other = c.devices.get(target)
                        if not other or target == dev.vol.offset or other[1].get('kind') != 'veth':
                            continue
                        peer_dev = other[0]
                        if not peer_dev.has_member('priv') or not isinstance(peer_dev.priv, objects.Array):
                            continue
                        if not peer_dev.has_member('priv_len') or offset + width > int(peer_dev.priv_len):
                            continue
                        back = int(c.obj('pointer', peer_dev.priv.vol.offset + offset)) & c.layer.address_mask
                        if back == dev.vol.offset:
                            matches.append((target, offset))
                    for target, offset in matches:
                        edges.append({'kind': 'veth_peer_candidate', 'source': row['address'], 'target': hex(target), 'evidence': hex(private_address + offset), 'private_relative_offset': offset, 'confidence': 'reciprocal_private_reference' if len(matches) == 1 else 'ambiguous', 'limitation': 'not a symbol-typed veth_priv.peer field'})
                    return
                priv = c.obj('veth_priv', private_address)
                edges.append({'kind': 'veth_peer', 'source': row['address'], 'target': hex(int(priv.peer)), 'evidence': hex(priv.vol.offset), 'confidence': 'direct_pointer'})
            c.read('topology.veth', dev, peer)
    return (edges, unsupported)

def topology_bridge_fdb(c, unsupported):
    rows = []
    for dev, interface in c.devices.values():
        if interface.get('kind') != 'bridge':
            continue

        def scan():
            if not dev.has_member('priv') or not isinstance(dev.priv, objects.Array):
                unsupported.append({'feature': 'bridge_fdb', 'interface': interface['address'], 'reason': 'no symbol-described inline private storage'})
                return
            bridge = c.obj('net_bridge', dev.priv.vol.offset)
            if int(bridge.dev) != dev.vol.offset:
                raise ValueError('bridge private dev backlink mismatch')
            for entry in c.hlist(bridge.fdb_list, 'net_bridge_fdb_entry', 'fdb_node'):

                def record():
                    rows.append({'address': hex(entry.vol.offset), 'namespace': interface['namespace'], 'bridge': interface['address'], 'interface': hex(int(entry.dst.dev)) if entry.dst else None, 'mac': ':'.join((f'{b:02x}' for b in c.layer.read(entry.key.addr.vol.offset, 6))), 'vlan': int(entry.key.vlan_id), 'flags': int(entry.flags), 'source': 'net_device.priv -> net_bridge.fdb_list -> net_bridge_fdb_entry', 'confidence': 'validated_bridge_backlink'})
                c.read('bridge.fdb.entry', entry, record)
        c.read('bridge.fdb', dev, scan)
    return rows

# Source section: sockets
"""FD sockets identified with each socket's own network namespace."""
import socket
from volatility3.framework.objects import utility
from volatility3.framework.symbols.linux import network

def sockets_fd_table(files, limit):
    """Select symbol-described layouts and validate bounds before allocation."""
    if files.has_member('fdt'):
        if not files.fdt:
            raise ValueError('NULL fdtable')
        table = files.fdt.dereference()
    elif files.has_member('fd') and files.has_member('max_fds'):
        table = files
    else:
        raise NotImplementedError('files_struct FD layout unavailable')
    count = int(table.max_fds)
    if not 0 <= count <= limit:
        raise ValueError(f'max_fds={count} outside safety budget 0..{limit}')
    if count and (not table.fd):
        raise ValueError('NULL fd pointer with nonempty fdtable')
    return (table, count)

def sockets_collect(c):
    network.NetSymbols.apply(c.context.symbol_space[c.kernel.symbol_table_name])
    rows = []
    files_cache = {}
    socket_fops = c.kernel.object_from_symbol('socket_file_ops').vol.offset
    inode_offset = c.kernel.get_type('socket_alloc').relative_child_offset('vfs_inode')
    for task in c.tasks:

        def task_fds():
            if not task.files:
                return
            files_key = int(task.files)
            if files_key in files_cache:
                rows.extend((dict(row, pid=int(task.pid)) for row in files_cache[files_key]))
                return
            start_row = len(rows)
            fdt, count = sockets_fd_table(task.files.dereference(), c.limit)
            if not count:
                files_cache[files_key] = []
                return
            fds = utility.array_of_pointers(fdt.fd.dereference(), count, c.kernel.symbol_table_name + '!file', c.context)
            for fd in range(count):

                def entry():
                    filp = fds[fd]
                    if not filp or int(filp.f_op) != socket_fops:
                        return
                    inode = filp.f_path.dentry.d_inode
                    alloc = c.obj('socket_alloc', int(inode) - inode_offset)
                    if not alloc.socket.sk:
                        return
                    sk = alloc.socket.sk.dereference()
                    common = sk.member('__sk_common')
                    ns = common.skc_net.net
                    row = {'pid': int(task.pid), 'fd': fd, 'file': hex(int(filp)), 'socket': hex(sk.vol.offset), 'namespace': hex(int(ns)), 'family': int(common.skc_family), 'source': 'task.files.fdt.fd -> socket_alloc.socket.sk', 'receive_queue_packets': int(sk.sk_receive_queue.qlen), 'state': int(common.skc_state)}
                    row['confidence'] = 'fd_reachable_socket_object'
                    row['socket_type'] = int(sk.sk_type)
                    row['protocol_number'] = int(sk.sk_protocol)
                    if row['family'] in (2, 10):
                        inet = sk.cast('inet_sock')
                        row['protocol'] = str(inet.get_protocol())
                        row['source_port'] = int(inet.get_src_port())
                        row['destination_port'] = int(inet.get_dst_port())
                        if row['family'] == 10:
                            row['source_ip'] = socket.inet_ntop(socket.AF_INET6, c.layer.read(common.skc_v6_rcv_saddr.vol.offset, 16))
                            row['destination_ip'] = socket.inet_ntop(socket.AF_INET6, c.layer.read(common.skc_v6_daddr.vol.offset, 16))
                        else:
                            row['source_ip'] = str(inet.get_src_addr())
                            row['destination_ip'] = str(inet.get_dst_addr())
                    elif row['family'] == 1:
                        unix = sk.cast('unix_sock')
                        row['path'] = None
                        if unix.addr:
                            length = int(unix.addr.len)
                            path_offset = c.kernel.get_type('sockaddr_un').relative_child_offset('sun_path')
                            if not path_offset <= length <= c.kernel.get_type('sockaddr_un').size:
                                raise ValueError('invalid sockaddr_un length')
                            raw = c.layer.read(unix.addr.name.vol.offset + path_offset, length - path_offset)
                            row['path_bytes_hex'] = raw.hex()
                            row['abstract'] = raw.startswith(b'\x00')
                            row['path'] = '@' + raw[1:].decode('utf-8', errors='backslashreplace') if row['abstract'] else raw.rstrip(b'\x00').decode('utf-8', errors='backslashreplace')
                        row['peer'] = hex(int(unix.peer))
                    rows.append(row)
                c.read('socket.fd', task, entry)
            files_cache[files_key] = rows[start_row:]
        c.read('socket.task', task, task_fds)
    unique = {}
    for row in rows:
        owner = {key: row[key] for key in ('pid', 'fd', 'file')}
        if row['socket'] not in unique:
            unique[row['socket']] = dict({key: value for key, value in row.items() if key not in ('pid', 'fd', 'file')}, holders=[])
        if owner not in unique[row['socket']]['holders']:
            unique[row['socket']]['holders'].append(owner)
    return list(unique.values())

# Source section: routes
"""Symbol-driven IPv4 trie and IPv6 FIB traversal.

Hash-size adapters follow include/net/{ip_fib,ip6_fib}.h: presence of the
CONFIG_*_MULTIPLE_TABLES-only rules_ops member selects the 256-bucket layout.
"""
import ipaddress
import socket
from volatility3.framework.objects import utility

def routes_nexthop(c, common):
    family = int(common.nhc_gw_family)
    gateway = None
    if family in (2, 10):
        gateway = socket.inet_ntop(socket.AF_INET if family == 2 else socket.AF_INET6, c.layer.read(common.nhc_gw.vol.offset, 4 if family == 2 else 16))
    return {'interface': hex(int(common.nhc_dev)), 'ifindex': int(common.nhc_oif), 'gateway': gateway, 'gateway_family': family, 'flags': int(common.nhc_flags)}

def routes_ipv4(c, ns, table, rows):
    from volatility3.framework import objects
    data = int(table.tb_data) if isinstance(table.tb_data, objects.Pointer) else table.tb_data.vol.offset
    root = c.obj('trie', data).kv[0]
    pending, seen = ([root], set())
    while pending:
        node = pending.pop()
        if node.vol.offset in seen or len(seen) >= c.limit:
            raise ValueError('IPv4 trie cycle or limit')
        seen.add(node.vol.offset)
        bits, pos = (int(node.bits), int(node.pos))
        if bits or pos:
            count = 1 if pos == 32 else 1 << bits
            if count > c.limit:
                raise ValueError('IPv4 trie fanout limit')
            children = utility.array_of_pointers(node.tnode, count, c.kernel.symbol_table_name + '!key_vector', c.context)
            pending.extend((p.dereference() for p in children if p))
            continue
        for alias in c.hlist(node.leaf, 'fib_alias', 'fa_list'):

            def entry():
                info = alias.fa_info.dereference()
                prefix = 32 - int(alias.fa_slen)
                cidr = str(ipaddress.ip_network((int(node.key), prefix), strict=False))
                row = {'address': hex(alias.vol.offset), 'namespace': ns['address'], 'family': 4, 'table': int(alias.tb_id) if alias.has_member('tb_id') else int(table.tb_id), 'destination': cidr, 'priority': int(info.fib_priority), 'protocol': int(info.fib_protocol), 'scope': int(info.fib_scope), 'type': int(alias.fa_type), 'nexthops': [], 'source': 'net.ipv4.fib_main/fib_default -> trie -> fib_alias -> fib_info', 'confidence': 'direct_pointer'}
                rows.append(row)
                if info.has_member('nh') and info.nh:
                    row['unresolved_nexthop_object'] = hex(int(info.nh))
                else:
                    for nh in c.array(info.fib_nh.vol.offset, 'fib_nh', int(info.fib_nhs)):
                        row['nexthops'].append(routes_nexthop(c, nh.nh_common))
            c.read('route.ipv4.entry', alias, entry)

def routes_ipv6(c, ns, table, rows):
    pending, seen, infos = ([table.tb6_root], set(), set())
    while pending:
        node = pending.pop()
        if node.vol.offset in seen or len(seen) >= c.limit:
            raise ValueError('IPv6 tree cycle or limit')
        seen.add(node.vol.offset)
        for field in ('left', 'right', 'subtree'):
            if node.has_member(field) and node.member(field):
                pending.append(node.member(field).dereference())
        ptr, chain = (node.leaf, set())
        while ptr:
            if int(ptr) in chain or len(chain) >= c.limit:
                raise ValueError('IPv6 route chain cycle or limit')
            chain.add(int(ptr))
            info = ptr.dereference()
            ptr = info.fib6_next
            if info.vol.offset in infos:
                continue
            infos.add(info.vol.offset)
            if int(info.fib6_table) != table.vol.offset:
                continue

            def entry():
                ip = socket.inet_ntop(socket.AF_INET6, c.layer.read(info.fib6_dst.addr.vol.offset, 16))
                row = {'address': hex(info.vol.offset), 'namespace': ns['address'], 'family': 6, 'table': int(table.tb6_id), 'destination': str(ipaddress.ip_network(f'{ip}/{int(info.fib6_dst.plen)}', strict=False)), 'priority': int(info.fib6_metric), 'protocol': int(info.fib6_protocol), 'flags': int(info.fib6_flags), 'nexthops': [], 'source': 'net.ipv6.fib6_*_tbl -> fib6_node -> fib6_info', 'confidence': 'direct_pointer'}
                rows.append(row)
                if info.has_member('nh') and info.nh:
                    row['unresolved_nexthop_object'] = hex(int(info.nh))
                else:
                    nh = c.obj('fib6_nh', info.fib6_nh.vol.offset)
                    row['nexthops'].append(routes_nexthop(c, nh.nh_common))
            c.read('route.ipv6.entry', info, entry)

def routes_collect(c, unsupported):
    rows = []
    unsupported.append({'feature': 'shared_nexthop', 'reason': 'nh object/group routes retain the pointer; shared nexthop groups not expanded'})
    for ns in c.nets.values():
        net, seen = (ns['object'], set())
        for family in (4, 6):

            def hashed_tables():
                block = net.ipv4 if family == 4 else net.ipv6
                rules_member = 'rules_ops' if family == 4 else 'fib6_rules_ops'
                count = 256 if block.has_member(rules_member) else 2 if family == 4 else 1
                typename, member = ('fib_table', 'tb_hlist') if family == 4 else ('fib6_table', 'tb6_hlist')
                for head in c.array(int(block.fib_table_hash), 'hlist_head', count):

                    def bucket():
                        for table in c.hlist(head, typename, member):
                            if table.vol.offset in seen:
                                continue
                            seen.add(table.vol.offset)
                            c.read('route.table', table, lambda: (routes_ipv4 if family == 4 else routes_ipv6)(c, ns, table, rows))
                    c.read('route.table_bucket', head, bucket)
            c.read('route.table_hash', net, hashed_tables)
        for family, field in ((4, 'fib_main'), (4, 'fib_default'), (6, 'fib6_main_tbl'), (6, 'fib6_local_tbl')):

            def table():
                block = net.ipv4 if family == 4 else net.ipv6
                if not block.has_member(field):
                    unsupported.append({'feature': 'route.' + field, 'namespace': ns['address'], 'reason': 'member absent'})
                    return
                ptr = block.member(field)
                if ptr and int(ptr) not in seen:
                    seen.add(int(ptr))
                    (routes_ipv4 if family == 4 else routes_ipv6)(c, ns, ptr.dereference(), rows)
            c.read('route.' + field, net, table)
    return list({(r['namespace'], r['address']): r for r in rows}.values())

def routes_rules(c):
    rows = []
    for ns in c.nets.values():
        for family, field in ((4, 'rules_ops'), (6, 'fib6_rules_ops')):

            def scan():
                block = ns['object'].ipv4 if family == 4 else ns['object'].ipv6
                if not block.has_member(field) or not block.member(field):
                    return
                for rule in c.walk(block.member(field).rules_list, 'fib_rule', 'list'):
                    row = {'address': hex(rule.vol.offset), 'namespace': ns['address'], 'family': family, 'source': 'net -> fib_rules_ops.rules_list -> fib_rule', 'confidence': 'direct_pointer', 'limitation': 'inventory, not a policy routing evaluator'}
                    rows.append(row)
                    for name in ('pref', 'table', 'action', 'flags', 'mark', 'mark_mask', 'iifindex', 'oifindex', 'l3mdev', 'ip_proto', 'suppress_prefixlen'):
                        if rule.has_member(name):
                            row[name] = c.read('rule.' + name, rule, lambda: int(rule.member(name)))
                    for name in ('iifname', 'oifname'):
                        row[name] = utility.array_to_string(rule.member(name))

                    def prefix_fields():
                        typename = 'fib4_rule' if family == 4 else 'fib6_rule'
                        offset = c.kernel.get_type(typename).relative_child_offset('common')
                        specific = c.obj(typename, rule.vol.offset - offset)
                        for name in ('src', 'dst'):
                            value = specific.member(name)
                            address = value.vol.offset if family == 4 else value.addr.vol.offset
                            length = int(specific.member(name + '_len')) if family == 4 else int(value.plen)
                            ip = socket.inet_ntop(socket.AF_INET if family == 4 else socket.AF_INET6, c.layer.read(address, 4 if family == 4 else 16))
                            row[name] = f'{ip}/{length}'
                    c.read('rule.prefix', rule, prefix_fields)
            c.read('rule.list', ns['object'], scan)
    return rows

# Source section: neighbors
"""ARP/NDP entries, including failed/incomplete states, not just MAC hits."""
import socket

def neighbors_collect(c, unsupported):
    rows = []
    for name in ('arp_tbl', 'nd_tbl'):
        if not c.kernel.has_symbol(name):
            unsupported.append({'feature': name, 'reason': 'symbol absent'})
            continue

        def table():
            tbl = c.kernel.object_from_symbol(name)
            family = int(tbl.family)
            nht = tbl.nht.dereference()
            shift = int(nht.hash_shift)
            if not 0 <= shift <= 20:
                raise ValueError('invalid neighbor hash_shift')
            heads = c.array(int(nht.hash_heads), 'hlist_head', 1 << shift)
            for head in heads:

                def bucket():
                    for n in c.hlist(head, 'neighbour', 'hash'):

                        def entry():
                            dev = n.dev.dereference()
                            size = int(tbl.key_len)
                            if size != (4 if family == 2 else 16):
                                raise ValueError('neighbor key length mismatch')
                            addr_len = int(dev.addr_len)
                            if not 0 <= addr_len <= 32:
                                raise ValueError('invalid MAC length')
                            rows.append({'address': hex(n.vol.offset), 'namespace': hex(int(dev.nd_net.net)), 'interface': hex(int(n.dev)), 'ifindex': int(dev.ifindex), 'family': family, 'ip': socket.inet_ntop(socket.AF_INET if family == 2 else socket.AF_INET6, c.layer.read(n.primary_key.vol.offset, size)), 'mac': ':'.join((f'{b:02x}' for b in c.layer.read(n.ha.vol.offset, addr_len))), 'nud_state': int(n.nud_state), 'dead': int(n.dead), 'source': name + '.nht.hash_heads', 'confidence': 'direct_pointer'})
                        c.read('neighbor.entry', n, entry)
                c.read('neighbor.bucket', head, bucket)
        c.read('neighbor.table', name, table)
    return rows

# Source section: conntrack
"""Confirmed conntrack tuples (observed flows, not firewall configuration)."""
import socket
from volatility3.framework.objects import utility

def conntrack_symbols(c, names):
    found = {n: c.kernel.object_from_symbol(n).vol.offset for n in names if c.kernel.has_symbol(n)}
    if len(found) == len(names):
        return found

    def modules():
        for mod in c.walk(c.kernel.object_from_symbol('modules'), 'module', 'list'):
            if utility.array_to_string(mod.name) != 'nf_conntrack':
                continue
            ks = mod.kallsyms.dereference()
            sym_type = ks.symtab.vol.subtype.vol.type_name.split('!')[-1]
            for sym in c.array(int(ks.symtab), sym_type, int(ks.num_symtab)):
                offset = int(sym.st_name)
                name = c.layer.read(int(ks.strtab) + offset, 128).split(b'\x00', 1)[0].decode('ascii', errors='replace')
                if name in names:
                    found[name] = int(sym.st_value) & c.layer.address_mask
    c.read('conntrack.module_symbols', 'modules', modules)
    return found

def conntrack_tuple_data(c, value):
    family, protocol = (int(value.src.l3num), int(value.dst.protonum))
    if family not in (2, 10):
        return {'family': family, 'protocol': protocol}
    size, af = (4, socket.AF_INET) if family == 2 else (16, socket.AF_INET6)
    row = {'family': family, 'protocol': protocol, 'source_ip': socket.inet_ntop(af, c.layer.read(value.src.u3.vol.offset, size)), 'destination_ip': socket.inet_ntop(af, c.layer.read(value.dst.u3.vol.offset, size))}
    if protocol in (6, 17, 33, 132, 136):
        row['source_port'] = int.from_bytes(c.layer.read(value.src.u.vol.offset, 2), 'big')
        row['destination_port'] = int.from_bytes(c.layer.read(value.dst.u.vol.offset, 2), 'big')
    return row

def conntrack_collect(c, unsupported):
    rows = []
    names = ('nf_conntrack_hash', 'nf_conntrack_htable_size')
    found = conntrack_symbols(c, names)
    if any((n not in found for n in names)):
        unsupported.append({'feature': 'conntrack', 'reason': 'hash symbols absent in kernel/module kallsyms'})
        return rows

    def scan():
        address = int(c.obj('pointer', found[names[0]]))
        count = int(c.obj('unsigned int', found[names[1]]))
        heads = c.array(address, 'hlist_nulls_head', count)
        entry_offset = c.kernel.get_type('nf_conntrack_tuple_hash').relative_child_offset('hnnode')
        tuples_offset = c.kernel.get_type('nf_conn').relative_child_offset('tuplehash')
        tuple_size = c.kernel.get_type('nf_conntrack_tuple_hash').size
        all_seen = set()
        for head in heads:

            def bucket():
                link, seen = (int(head.first), set())
                while link and (not link & 1):
                    if link in seen or len(seen) >= c.limit:
                        raise ValueError('conntrack cycle or limit')
                    seen.add(link)
                    entry = c.obj('nf_conntrack_tuple_hash', link - entry_offset)
                    direction = int(entry.tuple.dst.dir)
                    if direction not in (0, 1):
                        raise ValueError('invalid conntrack direction')
                    ct = c.obj('nf_conn', entry.vol.offset - tuples_offset - direction * tuple_size)
                    link = int(entry.hnnode.next)
                    if ct.vol.offset in all_seen:
                        continue
                    all_seen.add(ct.vol.offset)

                    def record():
                        status = int(ct.status)
                        rows.append({'address': hex(ct.vol.offset), 'namespace': hex(int(ct.ct_net.net)), 'original': conntrack_tuple_data(c, ct.tuplehash[0].tuple), 'reply': conntrack_tuple_data(c, ct.tuplehash[1].tuple), 'status': status, 'snat': bool(status & 1 << 4), 'dnat': bool(status & 1 << 5), 'source': 'nf_conntrack_hash -> tuplehash -> nf_conn', 'confidence': 'hashed_flow_object', 'limitation': 'flow state; does not enumerate configured NAT rules'})
                    c.read('conntrack.entry', ct, record)
            c.read('conntrack.bucket', head, bucket)
    c.read('conntrack.hash', found, scan)
    return rows

# Source section: multicast
"""Interface IPv4 IGMP and IPv6 MLD memberships (not multicast routes)."""
import socket

def multicast_collect(c):
    rows = []
    for dev, interface in c.devices.values():
        for family in (4, 6):

            def scan():
                ptr = dev.ip_ptr if family == 4 else dev.ip6_ptr
                if not ptr:
                    return
                ipdev = ptr.dereference().cast('in_device' if family == 4 else 'inet6_dev')
                ptr, seen = (ipdev.mc_list, set())
                while ptr:
                    if int(ptr) in seen or len(seen) >= c.limit:
                        raise ValueError('multicast list cycle or limit')
                    seen.add(int(ptr))
                    entry = ptr.dereference()
                    value = entry.multiaddr if family == 4 else entry.mca_addr
                    rows.append({'address': hex(entry.vol.offset), 'namespace': interface['namespace'], 'interface': interface['address'], 'family': family, 'group': socket.inet_ntop(socket.AF_INET if family == 4 else socket.AF_INET6, c.layer.read(value.vol.offset, 4 if family == 4 else 16)), 'users': int(entry.users if family == 4 else entry.mca_users), 'source': 'net_device.ip_ptr/ip6_ptr.mc_list', 'confidence': 'direct_pointer'})
                    ptr = entry.next
            c.read('multicast.list', dev, scan)
    return rows

# Source section: presentation
"""One ip-address/netstat-style table with independent interface and socket rows."""

def presentation_endpoint(ip, port):
    if not ip:
        return '-'
    return f'[{ip}]:{port}' if ':' in ip else f'{ip}:{port}'

def presentation_table(report, include_host=False):
    columns = ['Container', 'PID', 'NetNS', 'Interface', 'MAC', 'Address', 'Host link', 'Protocol', 'Local', 'Remote', 'State']
    nets = {n['address']: n for n in report['namespaces']}
    devs = {d['address']: d for d in report['interfaces']}
    tasks = {t['pid']: t for t in report['tasks']}
    sockets = {s['socket']: s for s in report['sockets']}
    selected = {a for a, n in nets.items() if include_host or n['container_candidates']}

    def ids(values):
        return ','.join((c[:12] for c in sorted(set(values)))) or '-'

    def name(address):
        return devs.get(address, {}).get('name', address or '-')

    def hostlink(device):
        links = []
        for edge in report['links']:
            if edge['source'] != device or edge['kind'] not in ('veth_peer', 'veth_peer_candidate'):
                continue
            bridges = [b for b in report['links'] if b['source'] == edge['target'] and b['kind'] == 'bridge_port']
            label = name(edge['target'])
            if bridges:
                label += ' -> ' + ','.join((name(b['target']) for b in bridges))
            if edge['kind'].endswith('candidate'):
                label += ' [candidate]'
            links.append(label)
        return '; '.join(links) or '-'
    states = {1: 'ESTABLISHED', 2: 'SYN_SENT', 3: 'SYN_RECV', 4: 'FIN_WAIT1', 5: 'FIN_WAIT2', 6: 'TIME_WAIT', 7: 'CLOSE', 8: 'CLOSE_WAIT', 9: 'LAST_ACK', 10: 'LISTEN', 11: 'CLOSING'}
    rows = []
    for ns in sorted(selected, key=lambda a: (str(nets[a].get('inode')), a)):
        net = nets[ns]
        inode = net.get('inode')
        pids = sorted({tasks[p]['tgid'] for p in net['pids'] if p in tasks})
        for device in sorted((d for d in devs.values() if d['namespace'] == ns), key=lambda d: (d['ifindex'], d['address'])):
            addresses = sorted({a['cidr'] for a in device['addresses']})
            for address in addresses or ['-']:
                rows.append([ids(net['container_candidates']), ','.join(map(str, pids)) or '-', inode, device['name'], device.get('mac'), address, hostlink(device['address']), '-', '-', '-', '-'])
        for sock in sorted((s for s in sockets.values() if s['namespace'] == ns), key=lambda s: (s['family'], s.get('protocol', ''), s.get('source_port', 0), s['socket'])):
            if sock['family'] not in (1, 2, 10):
                continue
            protocol = sock.get('protocol', 'UNIX')
            local = presentation_endpoint(sock.get('source_ip'), sock.get('source_port'))
            remote = presentation_endpoint(sock.get('destination_ip'), sock.get('destination_port'))
            state = states.get(sock['state'], str(sock['state']))
            if sock['family'] == 1:
                local = sock.get('path') or '(unnamed)'
                peer = sock.get('peer', '0x0')
                remote = '-' if peer == '0x0' else sockets.get(peer, {}).get('path') or '(unresolved peer)'
                if sock.get('socket_type') == 2:
                    state = 'UNCONN' if sock['state'] == 7 else state
            elif protocol == 'UDP' and sock['state'] == 7:
                state = 'UNCONN'
            owners = {(tasks.get(h['pid'], {}).get('tgid', h['pid']), ids(tasks.get(h['pid'], {}).get('container_candidates', []))) for h in sock['holders']}
            for pid, container in sorted(owners):
                rows.append([container, pid, inode, '-', '-', '-', '-', protocol, local, remote, state])
    return ([(c, str) for c in columns], [tuple(('-' if v is None else str(v).replace('\n', '\\n').replace('\t', '\\t') for v in row)) for row in rows])

# Source section: collector
"""Kernel objects are identities; IP prefixes and names are attributes only."""
import ipaddress
import re
import socket
import time
from volatility3.framework.objects import utility

class Collector:

    def __init__(self, context, kernel_name, limit=100000, identity_mode='combined', cgroup_cache=True):
        if not 1 <= limit <= 1000000:
            raise ValueError('limit must be in 1..1000000')
        self.context = context
        self.kernel = context.modules[kernel_name]
        self.layer = context.layers[self.kernel.layer_name]
        self.limit = limit
        if identity_mode not in ('combined', 'cgroup', 'shim'):
            raise ValueError('identity_mode must be combined, cgroup, or shim')
        self.identity_mode = identity_mode
        self.cgroup_cache_enabled = bool(cgroup_cache)
        self.cgroup_cache = {}
        self.errors = []
        self.nets = {}
        self.tasks = []
        self.devices = {}
        self.init_net_address = None
        self.metrics = {'timings_ns': {}, 'calls': {}, 'objects_visited': {}, 'termination': {}, 'cache': {'cgroup_hits': 0, 'cgroup_misses': 0}}

    def count(self, section, key, amount=1):
        if not hasattr(self, 'metrics'):
            self.metrics = {}
        bucket = self.metrics.setdefault(section, {})
        bucket[key] = bucket.get(key, 0) + amount

    def measure(self, name, fn):
        started = time.perf_counter_ns()
        try:
            return fn()
        finally:
            self.count('timings_ns', name, time.perf_counter_ns() - started)
            self.count('calls', name)

    def issue(self, stage, obj, exc):
        self.errors.append({'stage': stage, 'address': hex(obj.vol.offset) if hasattr(obj, 'vol') else str(obj), 'error': type(exc).__name__, 'detail': str(exc)})

    def read(self, stage, obj, fn, default=None):
        try:
            return fn()
        except Exception as exc:
            self.issue(stage, obj, exc)
            return default

    def obj(self, name, address):
        return self.kernel.object(name, offset=int(address), absolute=True)

    def walk(self, head, typename, member):
        """Walk list_head ourselves so corrupt links and truncation are reported."""
        seen = {int(head.vol.offset)}
        offset = self.kernel.get_type(typename).relative_child_offset(member)
        link = int(head.next)
        for _ in range(self.limit):
            if link == int(head.vol.offset):
                self.count('termination', 'list_head_return')
                return
            if not link or link in seen:
                self.count('termination', 'list_null_or_cycle')
                raise ValueError('null link or non-head cycle')
            seen.add(link)
            self.count('objects_visited', 'list:' + typename)
            obj = self.obj(typename, link - offset)
            yield obj
            link = int(obj.member(member).next)
        if link == int(head.vol.offset):
            self.count('termination', 'list_head_return')
            return
        self.count('termination', 'list_budget')
        raise ValueError('traversal limit reached')

    def cstring(self, ptr):
        return utility.pointer_to_string(ptr, count=4096) if ptr else ''

    def hlist(self, head, typename, member):
        offset = self.kernel.get_type(typename).relative_child_offset(member)
        link, seen = (int(head.first), set())
        while link:
            if link in seen or len(seen) >= self.limit:
                self.count('termination', 'hlist_cycle_or_budget')
                raise ValueError('hlist cycle or traversal limit')
            seen.add(link)
            self.count('objects_visited', 'hlist:' + typename)
            obj = self.obj(typename, link - offset)
            yield obj
            link = int(obj.member(member).next)

    def array(self, address, typename, count):
        if not 0 <= count <= self.limit:
            raise ValueError(f'array count {count} exceeds limit')
        self.count('objects_visited', 'array:' + typename, count)
        return self.kernel.object('array', offset=int(address), absolute=True, subtype=self.kernel.get_type(typename), count=count)

    def namespace(self, net, source):
        address = int(net.vol.offset)
        if address not in self.nets:
            self.nets[address] = {'object': net, 'address': hex(address), 'sources': [], 'pids': [], 'container_candidates': []}
            self.nets[address]['inode'] = self.read('net.inum', net, lambda: int(net.ns.inum) if net.has_member('ns') else int(net.proc_inum))
        if source not in self.nets[address]['sources']:
            self.nets[address]['sources'].append(source)
        return self.nets[address]

    def cgroups(self, task):
        if not task.cgroups:
            return []
        css = task.cgroups.dereference()
        cache_key = int(css.vol.offset)
        if self.cgroup_cache_enabled and cache_key in self.cgroup_cache:
            self.metrics['cache']['cgroup_hits'] += 1
            return list(self.cgroup_cache[cache_key])
        self.metrics['cache']['cgroup_misses'] += 1
        errors_before = len(self.errors)
        groups = {}

        def default_group():
            if css.has_member('dfl_cgrp') and css.dfl_cgrp:
                groups[int(css.dfl_cgrp)] = css.dfl_cgrp.dereference()
        self.read('cgroup.default', css, default_group)
        if css.has_member('subsys'):
            for index, state in enumerate(css.subsys):

                def subsystem():
                    if state and state.cgroup:
                        groups[int(state.cgroup)] = state.cgroup.dereference()
                self.read('cgroup.subsys.' + str(index), css, subsystem)
        paths = []
        for group in groups.values():
            path = self.read('cgroup.path', group, lambda: self.cgroup_path(group))
            if path is not None and path not in paths:
                paths.append(path)
        if self.cgroup_cache_enabled and len(self.errors) == errors_before:
            self.cgroup_cache[cache_key] = tuple(paths)
        return paths

    def cgroup_path(self, group):
        modern = group.has_member('kn')
        if modern and (not group.kn):
            raise ValueError('cgroup has NULL kernfs node')
        node = group.kn.dereference() if modern else group
        parts, seen = ([], set())
        while True:
            address = int(node.vol.offset)
            if address in seen:
                self.count('termination', 'kernfs_cycle')
                raise ValueError('cgroup parent cycle')
            if len(seen) >= self.limit:
                self.count('termination', 'kernfs_budget')
                raise ValueError('cgroup path budget exceeded')
            seen.add(address)
            self.count('objects_visited', 'kernfs_node' if modern else 'cgroup')
            if modern:
                parts.append(self.cstring(node.name))
            elif node.has_member('name'):
                parts.append(self.cstring(node.name))
            elif node.has_member('name_copy') and node.name_copy:
                parts.append(utility.array_to_string(node.name_copy.name))
            else:
                raise NotImplementedError('cgroup name layout unavailable')
            parent = node.parent if node.has_member('parent') else node.member('__parent')
            if not parent:
                self.count('termination', 'kernfs_root')
                return '/' + '/'.join((p for p in reversed(parts) if p))
            node = parent.dereference()

    def collect_tasks(self):
        init = self.kernel.object_from_symbol('init_task')

        def scan():
            for task in self.walk(init.tasks, 'task_struct', 'tasks'):
                self.tasks.append(task)
        self.read('tasks.list', init, scan)
        seen = {t.vol.offset for t in self.tasks}
        for leader in list(self.tasks):

            def threads():
                if leader.has_member('thread_node') and leader.signal.has_member('thread_head'):
                    head, member = (leader.signal.thread_head, 'thread_node')
                elif leader.has_member('thread_group'):
                    head, member = (leader.thread_group, 'thread_group')
                else:
                    raise NotImplementedError('thread list layout unavailable')
                for task in self.walk(head, 'task_struct', member):
                    if task.vol.offset not in seen:
                        seen.add(task.vol.offset)
                        self.tasks.append(task)
            self.read('tasks.threads', leader, threads)
        records = []
        for task in self.tasks:
            record = self.read('task.identity', task, lambda: {'address': hex(task.vol.offset), 'pid': int(task.pid), 'tgid': int(task.tgid), 'comm': utility.array_to_string(task.comm), 'container_candidates': [], 'source': 'init_task.tasks + task thread lists', 'confidence': 'reachable_task_object'})
            if record is None:
                continue
            paths = self.read('task.cgroups', task, lambda: self.measure('identity.cgroup_paths', lambda: self.cgroups(task)), []) if self.identity_mode in ('combined', 'cgroup') else []
            record['cgroup_paths'] = paths
            for path in paths:
                for cid in re.findall('(?<![0-9a-f])([0-9a-f]{64})(?![0-9a-f])', path):
                    if cid not in record['container_candidates']:
                        record['container_candidates'].append(cid)
            record['identity_evidence'] = 'cgroup_path_candidate' if record['container_candidates'] else 'unresolved'
            proxy = self.read('task.nsproxy', task, lambda: task.nsproxy.dereference() if task.nsproxy else None)
            if proxy is not None:
                net = self.read('task.net', task, lambda: proxy.net_ns.dereference() if proxy.net_ns else None)
                if net is not None:
                    ns = self.namespace(net, 'task.nsproxy.net_ns')
                    ns['pids'].append(record['pid'])
                    ns['container_candidates'] = sorted(set(ns['container_candidates'] + record['container_candidates']))
                    record['namespace'] = ns['address']
            records.append(record)
        return records

    def address(self, ifa, family):
        if family == 4:
            raw = self.layer.read(ifa.ifa_local.vol.offset, 4)
            prefix = int(ifa.ifa_prefixlen)
            flags, scope = (int(ifa.ifa_flags), int(ifa.ifa_scope))
        else:
            raw = self.layer.read(ifa.addr.vol.offset, 16)
            prefix = int(ifa.prefix_len)
            flags, scope = (int(ifa.flags), int(ifa.scope))
        ip = socket.inet_ntop(socket.AF_INET if family == 4 else socket.AF_INET6, raw)
        cidr = f'{ip}/{prefix}'
        return {'address': hex(ifa.vol.offset), 'family': family, 'ip': ip, 'prefix': prefix, 'cidr': cidr, 'subnet': str(ipaddress.ip_network(cidr, strict=False)), 'flags': flags, 'scope': scope}

    def interface(self, net, dev):
        row = {'address': hex(dev.vol.offset), 'namespace': net['address'], 'namespace_inode': net['inode'], 'container_candidates': net['container_candidates'], 'pids': net['pids'], 'name': utility.array_to_string(dev.name), 'ifindex': int(dev.ifindex), 'addresses': [], 'source': 'kernel.net.dev_base_head', 'confidence': 'direct_object_membership'}
        row['device_namespace'] = self.read('interface.nd_net', dev, lambda: hex(int(dev.nd_net.net)))
        if row['device_namespace'] is not None and row['device_namespace'] != net['address']:
            row['confidence'] = 'conflicting_namespace_pointers'
            self.issue('interface.namespace_conflict', dev, ValueError('dev_base_head and nd_net disagree'))
        for field in ('mtu', 'flags', 'promiscuity', 'operstate', 'type'):
            row[field] = self.read('interface.' + field, dev, lambda: int(dev.member(field)))

        def mac():
            size = int(dev.addr_len)
            if not 0 <= size <= 32:
                raise ValueError('invalid hardware address length')
            return ':'.join((f'{b:02x}' for b in self.layer.read(int(dev.dev_addr), size)))
        row['mac'] = self.read('interface.mac', dev, mac)
        if dev.has_member('rtnl_link_ops') and dev.rtnl_link_ops:
            row['kind'] = self.read('interface.kind', dev, lambda: self.cstring(dev.rtnl_link_ops.kind))

        def ipv4():
            if not dev.has_member('ip_ptr') or not dev.ip_ptr:
                return
            ipdev = dev.ip_ptr.dereference().cast('in_device')
            ptr, seen = (ipdev.ifa_list, set())
            for _ in range(self.limit):
                if not ptr:
                    return
                if int(ptr) in seen:
                    raise ValueError('IPv4 address cycle')
                seen.add(int(ptr))
                ifa = ptr.dereference()
                value = self.read('ipv4.entry', ifa, lambda: self.address(ifa, 4))
                if value:
                    row['addresses'].append(value)
                ptr = ifa.ifa_next
            if ptr:
                raise ValueError('IPv4 address limit')

        def ipv6():
            if not dev.has_member('ip6_ptr') or not dev.ip6_ptr:
                return
            ipdev = dev.ip6_ptr.dereference().cast('inet6_dev')
            for ifa in self.walk(ipdev.addr_list, 'inet6_ifaddr', 'if_list'):
                value = self.read('ipv6.entry', ifa, lambda: self.address(ifa, 6))
                if value:
                    row['addresses'].append(value)
        self.read('interface.ipv4', dev, ipv4)
        self.read('interface.ipv6', dev, ipv6)
        self.devices[int(dev.vol.offset)] = (dev, row)
        return row

    def collect(self, features=None):
        enabled = lambda name: features is None or name in features
        if self.kernel.has_symbol('init_net'):
            initial = self.kernel.object_from_symbol('init_net')
            self.init_net_address = hex(initial.vol.offset)
            self.namespace(initial, 'init_net')
        tasks = self.measure('discovery.tasks', self.collect_tasks)
        published = self.measure('identity.runtime_and_ancestry', lambda: identity_collect(self, tasks))

        def namespaces():
            head = self.kernel.object_from_symbol('net_namespace_list')
            for net in self.walk(head, 'net', 'list'):
                self.namespace(net, 'net_namespace_list')
        self.measure('discovery.namespaces', lambda: self.read('net.list', 'net_namespace_list', namespaces))
        interfaces = []
        for net in self.nets.values():

            def devices():
                for dev in self.walk(net['object'].dev_base_head, 'net_device', 'dev_list'):
                    value = self.read('interface', dev, lambda: self.interface(net, dev))
                    if value:
                        interfaces.append(value)
            self.measure('network.interfaces', lambda: self.read('net.devices', net['object'], devices))
        edges, unsupported = self.measure('network.topology', lambda: topology_collect(self))
        socket_rows = self.measure('network.sockets', lambda: self.read('socket.collect', 'kernel', lambda: sockets_collect(self), [])) if enabled('sockets') else []
        route_rows = self.measure('network.routes', lambda: self.read('route.collect', 'kernel', lambda: routes_collect(self, unsupported), [])) if enabled('routes') else []
        neighbor_rows = self.measure('network.neighbors', lambda: self.read('neighbor.collect', 'kernel', lambda: neighbors_collect(self, unsupported), [])) if enabled('neighbors') else []
        flow_rows = self.measure('network.conntrack', lambda: self.read('conntrack.collect', 'kernel', lambda: conntrack_collect(self, unsupported), [])) if enabled('conntrack') else []
        multicast_rows = self.measure('network.multicast', lambda: self.read('multicast.collect', 'kernel', lambda: multicast_collect(self), [])) if enabled('multicast') else []
        rule_rows = self.measure('network.rules', lambda: self.read('rule.collect', 'kernel', lambda: routes_rules(self), [])) if enabled('rules') else []
        fdb_rows = self.measure('network.bridge_fdb', lambda: self.read('bridge.collect', 'kernel', lambda: topology_bridge_fdb(self, unsupported), [])) if enabled('bridge_fdb') else []
        unsupported.extend([{'feature': 'firewall_rules', 'reason': 'nftables/iptables rule programs not decoded; conntrack and proxy argv are separate evidence'}, {'feature': 'runtime_network_metadata', 'reason': 'Docker network ID/name/IPAM/options require runtime metadata; not inferred from prefixes'}, {'feature': 'socket_coverage', 'reason': 'FD-reachable sockets only; orphan/TIME_WAIT/hash-only sockets not enumerated'}])
        for ns in self.nets.values():
            ns['is_initial'] = ns['address'] == self.init_net_address
            ns['membership'] = 'host_shared_candidate' if ns['is_initial'] and ns['container_candidates'] else 'identified_candidates' if ns['container_candidates'] else 'unattributed'
        return {'schema_version': 1, 'tasks': tasks, 'links': edges, 'unsupported': unsupported, 'sockets': socket_rows, 'metadata': {'kernel_symbol_table': self.kernel.symbol_table_name, 'kernel_layer': self.kernel.layer_name, 'requested_features': sorted(features) if features is not None else ['all_supported'], 'kernel_virtual_offset': hex(self.kernel.offset), 'traversal_limit': self.limit, 'traversal_limit_semantics': 'corruption safety budget; normal termination uses head/null/root and cycle detection', 'identity_mode': self.identity_mode, 'cgroup_cache': self.cgroup_cache_enabled, 'metrics': self.metrics, 'identity_policy': 'object address within this snapshot; namespace inode and ifindex are attributes', 'snapshot_limit': 'a live-acquired dump may contain temporal smearing; successful parsing is not exhaustive coverage'}, 'routes': route_rows, 'neighbors': neighbor_rows, 'published_ports': published, 'conntrack': flow_rows, 'multicast': multicast_rows, 'rules': rule_rows, 'bridge_fdb': fdb_rows, 'namespaces': [{k: v for k, v in ns.items() if k != 'object'} for ns in self.nets.values()], 'interfaces': interfaces, 'errors': self.errors, 'summary': {'tasks': len(tasks), 'namespaces': len(self.nets), 'interfaces': len(interfaces), 'addresses': sum((len(i['addresses']) for i in interfaces)), 'sockets': len(socket_rows), 'links': len(edges), 'routes': len(route_rows), 'rules': len(rule_rows), 'neighbors': len(neighbor_rows), 'conntrack': len(flow_rows), 'multicast': len(multicast_rows), 'bridge_fdb': len(fdb_rows), 'published_ports': len(published), 'errors': len(self.errors)}}

# Source section: plugin
"""Container attachment reconstruction with opt-in detailed evidence."""
import json
import logging
from volatility3.framework import interfaces, renderers
from volatility3.framework.configuration import requirements
from volatility3.framework.symbols.linux import network
vollog = logging.getLogger(__name__)

class InspectNetworks(interfaces.plugins.PluginInterface):
    _required_framework_version = (2, 22, 0)
    _version = (3, 0, 0)

    @classmethod
    def get_requirements(cls):
        return [requirements.ModuleRequirement(name='kernel', description='Linux kernel', architectures=['Intel32', 'Intel64']), requirements.VersionRequirement(name='net_symbols', component=network.NetSymbols, version=(1, 0, 0)), requirements.IntRequirement(name='limit', description='Corruption safety budget per traversal', default=100000, optional=True), requirements.StringRequirement(name='identity-mode', description='Container identity strategy: combined, cgroup, or shim', default='combined', optional=True), requirements.BooleanRequirement(name='disable-cgroup-cache', description='Benchmark-only: recompute cgroup paths for every task/thread', default=False, optional=True), requirements.BooleanRequirement(name='identity-only', description='Benchmark-only: skip socket and optional network collectors', default=False, optional=True), requirements.BooleanRequirement(name='include-host', description='Include host/unattributed namespaces', default=False, optional=True), requirements.BooleanRequirement(name='containers-only', description='Compatibility alias for default scope', default=False, optional=True), requirements.BooleanRequirement(name='dump-evidence', description='Collect all supported evidence and save JSON', default=False, optional=True), requirements.BooleanRequirement(name='dump-metrics', description='Save traversal/timing metrics without enabling optional evidence collectors', default=False, optional=True)]

    def run(self):
        features = set() if self.config['identity-only'] else None if self.config['dump-evidence'] else {'sockets'}
        report = Collector(self.context, self.config['kernel'], self.config['limit'], identity_mode=self.config['identity-mode'], cgroup_cache=not self.config['disable-cgroup-cache']).collect(features=features)
        if self.config['dump-evidence']:
            with self.open('network_evidence.json') as handle:
                handle.write(json.dumps(report, indent=2, ensure_ascii=False).encode('utf-8'))
        if self.config['dump-metrics']:
            payload = {'metadata': report['metadata'], 'summary': report['summary'], 'container_candidates': sorted({cid for task in report['tasks'] for cid in task['container_candidates']}), 'identity_assignments': [{'pid': task['pid'], 'tgid': task['tgid'], 'container_candidates': task['container_candidates'], 'evidence': task.get('identity_evidence'), 'conflict': task.get('identity_conflict', False)} for task in report['tasks'] if task['container_candidates']], 'errors': report['errors']}
            with self.open('network_metrics.json') as handle:
                handle.write(json.dumps(payload, indent=2, ensure_ascii=False).encode('utf-8'))
        if report['errors']:
            vollog.warning('%d parsing errors: partial result. Use --dump-evidence for error details.', len(report['errors']))
        if not any((n['container_candidates'] for n in report['namespaces'])) and (not self.config['include-host']):
            vollog.warning('No attributed container namespaces. Use --include-host to inspect unattributed namespaces.')
        columns, rows = presentation_table(report, self.config['include-host'] and (not self.config['containers-only']))
        return renderers.TreeGrid(columns, ((0, row) for row in rows))
